Repository kyma-project/subscription-cleanup-job, pull requests merged in 2024-01, with the labels that each got.

#1 Create sec-scanners-config
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
  sec-scanners-config
Labels: cla: yes, size/M, lgtm

#2 Create Dockerfile.job
  Dockerfile.job
Labels: cla: yes, size/S, lgtm

#12 Create README.md
  README.md
Labels: cla: yes, size/XS, lgtm

#14 Remove Gophers as codeowners
  CODEOWNERS
Labels: cla: yes, size/XS, lgtm

#15 updates golang to 1.21.5-alpine3.19
  Dockerfile.job
  sec-scanners-config
Labels: cla: yes, size/XS, lgtm
