Repository kyma-project/subscription-cleanup-job, pull requests merged in 2024-11, with the labels that each got.

#31 Create dependabot.yml
  .github/dependabot.yml
Labels: cla: yes, size/S, lgtm

#33 Register Reuse for subscription-cleanup-job
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: cla: yes, lgtm, size/L

#35 improves dependabot grouping for k8s.io dependencies
  .github/dependabot.yml
Labels: cla: yes, size/XS, lgtm
