Repository kyma-project/subscription-cleanup-job, pull requests merged in 2024-09, with the labels that each got.

#16 docs: Add missing files and sections
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: cla: yes, lgtm, size/L

#17 Rename sec-config file: add missing yaml extension
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#18 Add support for gcp_cf-sa30 hyperscaler type
  cmd/subscriptioncleanup/cloudprovider/factory.go
  cmd/subscriptioncleanup/cloudprovider/mocks/ProviderFactory.go
  cmd/subscriptioncleanup/job/cleaner.go
  cmd/subscriptioncleanup/job/cleaner_test.go
  cmd/subscriptioncleanup/main.go
  cmd/subscriptioncleanup/model/types.go
Labels: cla: yes, size/S, lgtm

#20 Migrate build job to GHA
  .github/workflows/build.yaml
Labels: cla: yes, size/M, lgtm

#21 Fix dockerfile
  Dockerfile.job
Labels: cla: yes, size/XS, lgtm
