Repository kyma-project/subscription-cleanup-job, pull requests merged in 2024-10, with the labels that each got.

#26 Bump libraries
  go.mod
  go.sum
Labels: cla: yes, size/M, lgtm

#27 Bump image and apimachinery
  Dockerfile.job
  go.mod
Labels: cla: yes, size/XS, lgtm

#29 Bump dependencies
  go.mod
  go.sum
Labels: cla: yes, size/S, lgtm

#30 Fix sec-config file
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm
